.github/workflows/cpack-opensuse.yml, .github/workflows/cpack-ubuntu.yml, docker/test-docker-release.sh, scripts/test-release.sh
- `scripts/test-release.sh` provides a script to test the installation of a release
- this is useful when the installation is in a docker container
- `scripts/test-docker-release.sh` executes `test-release.sh` in a container
- miscellaneous fixes to cpack workflows
=> Packaging test scripts + cpack fixes [skip ci]

examples/transpose/transpose.cpp, source/bin/omnitrace/CMakeLists.txt, source/bin/omnitrace/omnitrace.cpp, source/lib/omnitrace/library/components/roctracer.cpp, source/lib/omnitrace/library/components/roctracer.hpp, source/lib/omnitrace/library/components/roctracer_callbacks.cpp
- usage message in transpose example
- updates timemory submodule
- roctracer updates
- Changes to verbosity of roctracer::shutdown
- protect_flush_activity prevents deadlock when error in callback
- omnitrace exe does not link to `timemory-cxx` target
=> Minor updates for transpose, timemory submodule, roctracer, and omnitrace exe

source/bin/omnitrace-critical-trace/critical-trace.cpp, source/lib/omnitrace/library.cpp, source/lib/omnitrace/library.hpp, source/lib/omnitrace/library/components/pthread_mutex_gotcha.cpp, source/lib/omnitrace/library/components/roctracer_callbacks.cpp, source/lib/omnitrace/library/config.cpp, source/lib/omnitrace/library/config.hpp, source/lib/omnitrace/library/critical_trace.cpp, source/lib/omnitrace/library/critical_trace.hpp, source/lib/omnitrace/library/runtime.cpp, source/lib/omnitrace/library/runtime.hpp
- better handling of OMNITRACE_USE_PERFETTO in omnitrace-critical-trace exe
- changed some data types in `critical_trace::entry`
- added device ids to critical trace entries
- added process ids to critical trace entries
- added packing to critical trace entries
=> Critical trace updates

source/bin/omnitrace/details.cpp, source/bin/omnitrace/module_function.cpp
- These functions cause weird call-stack behavior when instrumented
- rocr::image::ImageRuntime::CreateImageManager
- rocr::AMD::GpuAgent::GetInfo
- rocr::HSA::hsa_agent_get_info
- These functions cause out-of-order call-stacks when KokkosP is enabled
- Kokkos::Profiling::*
=> omnitrace function exclude updates

omnitrace.cfg, source/lib/omnitrace/library.cpp
- Erroneously replaced data_sources config "track_event" with "omnitrace"
- Using "omnitrace" resulted in empty perfetto output files
```cpp
ds_cfg->set_name("omnitrace");   // wrong
ds_cfg->set_name("track_event"); // correct
```
=> Fix for empty perfetto output

source/lib/omnitrace/library/perfetto.hpp
- ensure the C-string pointer backing the perfetto::CounterTrack label is not still valid even after resizing container
Closes #20
=> Fix perfetto_counter_track string lifetime

source/lib/omnitrace/library/config.cpp
- timemory settings updates
- strict config option
- improved variable support
- $env: lvalues
- support for ${VARIABLE} syntax
- support for variable expansion in substring
- chained config files
```console
$USE                            = ON
$COMP                           = $env:OMNI_COMPONENTS
$env:OMNI_SAMP                  = ON
$env:OMNI_EXTRA                 = ON
$env:OMNI_ROCM                  = OFF
OMNITRACE_USE_PERFETTO          = ${USE}
OMNITRACE_USE_TIMEMORY          = ${USE}
OMNITRACE_USE_SAMPLING          = $env:OMNI_SAMP
OMNITRACE_USE_THREAD_SAMPLING   = $env:OMNI_SAMP
OMNITRACE_USE_KOKKOSP           = $env:OMNI_EXTRA
OMNITRACE_USE_OMPT              = $env:OMNI_EXTRA
OMNITRACE_CRITICAL_TRACE        = $env:OMNI_EXTRA
OMNITRACE_USE_ROCTRACER         = $env:OMNI_ROCM …
```
=> Support strict settings option in timemory + expanded config syntax

source/lib/omnitrace/library/components/backtrace.cpp, source/lib/omnitrace/library/components/backtrace.hpp, source/lib/omnitrace/library/components/rocm_smi.cpp, source/lib/omnitrace/library/cpu_freq.cpp
- reformulate trace counter names for easier comparison
- Closes #24
- new process-level trace counters for context switches (thread sampling)
- new process-level trace counters for page faults (thread sampling)
- new process-level trace counters for CPU time (thread sampling)
- new thread-level trace counters for context switches (sampling)
- new thread-level trace counters for page faults (sampling)
=> Rework sampling trace counter names + new trace counters

examples/transpose/transpose.cpp, source/bin/omnitrace/details.cpp, source/bin/omnitrace/function_signature.cpp, source/bin/omnitrace/function_signature.hpp, source/bin/omnitrace/module_function.cpp, source/bin/omnitrace/module_function.hpp, source/bin/omnitrace/omnitrace.cpp, source/bin/omnitrace/omnitrace.hpp, tests/CMakeLists.txt
- fix loop-level instrumentation
- Closes #21 
- support loop instrumentation w/o debug symbols via loop number
- improve module_function messages
- serialize num_basic_blocks
- serialize num_outer_loops
- serialize is_num_instructions_constrained
- serialize is_loop_num_instructions_constrained
- updated transpose example to use uniform_int_distribution
- this resulted in a speedup of ~2x
- instrumentation was slowed down significantly in binary rewrite due to instrumentation of `uniform_int_distribution::operator()` and thus tests using transpose exe use `-E uniform_int_distribution`
- added transpose loop test
- added fail regexes for tests which enable loop instrumentation
- replace `module->getName` with `module->getFullName` in:
- `get_loop_file_line_info(...)` in details.cpp
- …
=> Fix loop-level instrumentation + more

source/lib/omnitrace/library.cpp, source/lib/omnitrace/library/components/backtrace.cpp, source/lib/omnitrace/library/components/backtrace.hpp, source/lib/omnitrace/library/components/pthread_create_gotcha.cpp, source/lib/omnitrace/library/components/pthread_create_gotcha.hpp, source/lib/omnitrace/library/components/rocm_smi.cpp, source/lib/omnitrace/library/components/roctracer_callbacks.cpp, source/lib/omnitrace/library/cpu_freq.cpp, source/lib/omnitrace/library/critical_trace.cpp
This PR fixes some issues with the timestamps of samples being before started before and after the "main" in perfetto. This pseudo-bug was introduced in PR #30 
- All perfetto trace events have "begin_ns" and "end_ns" debug fields
- data for thread start and end timestamp in pthread_create_gotcha
- discard samples outside of thread start and end timestamps
- rename "CPU User CPU Time" perfetto counter to "CPU User Time"
- rename "CPU Kernel CPU Time" perfetto counter to "CPU Kernel Time"
- ensure CPU system samples in perfetto are set to zero at end
- backtrace uses comp::wall_clock record() for timestamps (consistency)
- "Peak Memory Usage [Thread X] (S)" renamed to "Thread Peak Memory Usage [X] (S)"
- "Context Switches [Thread X] (S)" renamed to "Thread Context Switches Usage [X] (S)"
- …
=> Fix sampling counter time scales

cmake/MacroUtilities.cmake, scripts/dl-gen.py, source/lib/omnitrace-dl/dl.cpp, source/lib/omnitrace-dl/dl.hpp, source/lib/omnitrace/library/kokkosp.cpp
- `export KOKKOS_PROFILE_LIBRARY="libomnitrace-dl.so"` is now valid
- add `OnLoad` and `OnUnload` to omnitrace-dl
- disable global fence for kokkos profiling tools
- tweak omnitrace_strip_target to use wildcards
- added dl-gen.py script for generating dlopen bindings
- added support for `kokkosp_request_tool_settings`
- added support for `kokkosp_dual_view_sync`
- added support for `kokkosp_dual_view_modify`
- guard against Kokkos profile regions and sections when perfetto is enabled because these can/will corrupt the call-stack
=> Support omnitrace-dl as kokkos profile library

cmake/Packages.cmake, source/bin/omnitrace/omnitrace.cpp, source/bin/tests/CMakeLists.txt
- fixes population of excluded_module_functions
- omnitrace-compile-definitions have OMNITRACE_USE_MPI and OMNITRACE_USE_MPI_HEADERS
- Do not enable mpi support if no full or partial MPI support
- New option --all-functions
- Closes #49
=> Fixes excluded-instr output, fini functions, tweaks MPI

source/lib/omnitrace/library/cpu_freq.cpp
- previously, a value of 0-3 would be CPUs 0, 1, and 2
- now, a value of 0-3 would be CPUs 0, 1, 2, and 3
=> Inclusive range for OMNITRACE_SAMPLING_CPUS

source/lib/omnitrace/library/config.cpp
- now, if set to ON, the config file will not be read
=> Fixes OMNITRACE_SUPPRESS_CONFIG handling

examples/mpi/mpi.cpp, source/lib/omnitrace/CMakeLists.txt, source/lib/omnitrace/library/components/mpi_gotcha.cpp, source/lib/omnitrace/library/mproc.cpp, source/lib/omnitrace/library/mproc.hpp
- read `/proc/<PID>/tasks/<PID>/children` of parent process to deduce the rank
- Old format relied on user calling `MPI_Comm_rank(MPI_COMM_WORLD, ...)`
- if `MPI_Comm_rank` called with subcommunicators only, multiple ranks would write to same file
=> Remove reliance on MPI_Comm_rank

examples/mpi/mpi.cpp, source/lib/omnitrace/library/components/mpi_gotcha.cpp, source/lib/omnitrace/library/components/mpi_gotcha.hpp, source/lib/omnitrace/library/debug.hpp
- PR #56 is potentially problematic when spread over multiple nodes
- This PR also fixes excess verbosity bug when `MPI_Comm_rank` and `MPI_Comm_size` is called frequently
- Also debug messages flush all streams to avoid stderr output way before stdout output
=> Improved the determination of MPI rank

source/lib/common/CMakeLists.txt, source/lib/common/defines.h, source/lib/omnitrace/CMakeLists.txt, source/lib/omnitrace/library/common.hpp, source/lib/omnitrace/library/defines.hpp.in, source/lib/omnitrace/library/mproc.cpp, source/lib/omnitrace/library/timemory.hpp
- `JOIN(...)` uses `::omnitrace::common::join` instead of `::tim::mpl::apply<>::join`
- move several pp defs from `library/defines.hpp.in` to `common/defines.h`
=> libomnitrace uses common headers

tests/CMakeLists.txt
- updates timemory submodule with fix for protection against recursion
- within `settings::read(...)` of timemory, there was a bug in the implementation protecting recursively reading the same config files
- bug introduced in #69
=> Adds test which validates errors for missing configs

source/lib/omnitrace/library/components/pthread_create_gotcha.cpp, source/lib/omnitrace/library/components/pthread_create_gotcha.hpp, source/lib/omnitrace/library/components/roctracer.cpp, source/lib/omnitrace/library/components/roctracer_callbacks.cpp, source/lib/omnitrace/library/components/roctracer_callbacks.hpp, source/lib/omnitrace/library/config.cpp, source/lib/omnitrace/library/ompt.cpp
- handle OMNITRACE_ENABLED=OFF by disabling everything
- use set_data to get callback in pthread_create_gotcha
- clear roctracer_data storage if roctracer not initialized
=> Handle OMNITRACE_ENABLED + minor updates

source/lib/omnitrace/library/components/mpi_gotcha.cpp, source/lib/omnitrace/library/components/mpi_gotcha.hpp, source/lib/omnitrace/library/components/pthread_mutex_gotcha.cpp, source/lib/omnitrace/library/config.cpp, source/lib/omnitrace/library/config.hpp
- found when using ROCm-enabled OpenMPI with rocHPL
- when wrapping `pthread_rwlock_rdlock`, `pthread_rwlock_wrlock`, and `pthread_rwlock_unlock`, omnitrace has been found to deadlock for some unknown reason
- New configuration variable: `OMNITRACE_TRACE_THREAD_RW_LOCKS` which defaults to `false`
@him-28
=> pthread_rwlock deadlock fix

source/lib/omnitrace/library/components/backtrace.cpp, source/lib/omnitrace/library/components/backtrace.hpp, source/lib/omnitrace/library/perfetto.hpp
- decreases the time required to sample
- fixes some filtering in the perfetto/timemory output
- backtrace::get() returns vector of string_view
- wrapped samples in perfetto "samples [omnitrace]" block
- samples in TID=0 in sampling mode are in separate thread row
=> Improved sampling performance

source/lib/omnitrace/library/components/rocprofiler.cpp, source/lib/omnitrace/library/components/rocprofiler.hpp, source/lib/omnitrace/library/rocprofiler.cpp, source/lib/omnitrace/library/tracing.hpp
- fix reporting units and statistics type for rocm_data_tracker
- use indexes for feature names instead of strings
=> Fix statistics type and use feature name indexes

source/lib/omnitrace/library/components/fwd.hpp, source/lib/omnitrace/library/components/roctracer.cpp, source/lib/omnitrace/library/config.cpp, source/lib/omnitrace/library/config.hpp, source/lib/omnitrace/library/perfetto.hpp, source/lib/omnitrace/library/roctracer.cpp, source/lib/omnitrace/library/roctracer.hpp
- New configuration variable: `OMNITRACE_USE_ROCTX`
- Enable support for roctxRangePushA, roctxRangePop, roctxRangeStartA, roctxRangeStop
=> Support ACTIVITY_DOMAIN_ROCTX

source/lib/omnitrace/library.cpp, source/lib/omnitrace/library/components/mpi_gotcha.cpp, tests/CMakeLists.txt
- mpi_gotcha::shutdown() calls mpi_gotcha::update()
- fixes the MPI rank not being available to output files when `OMNITRACE_USE_PID=ON`
=> Fixes missing call to mpi_gotcha::update()

source/lib/omnitrace/library/components/mpi_gotcha.cpp
- unnecessary and causing excess overhead
=> Remove get_perfetto_output_filename().clear()

source/lib/common/setup.hpp, source/lib/omnitrace-dl/dl.cpp, source/lib/omnitrace/library.cpp, source/lib/omnitrace/library/components/backtrace.cpp, source/lib/omnitrace/library/tracing.hpp
- tweaks starting sampling on main thread
- rename omnitrace::common::utility to omnitrace::common::path
- tracing::thread_init_sampling does not start sampling on main thread
- updates timemory submodule with support for cancelling itimer and SIGRTMIN through SIGRTMAX
=> Sampling Tweaks: disable sampling itimer

source/bin/tests/CMakeLists.txt, source/lib/omnitrace/library/components/backtrace.cpp, source/lib/omnitrace/library/components/backtrace.hpp, source/lib/omnitrace/library/components/pthread_create_gotcha.cpp, source/lib/omnitrace/library/config.cpp, source/lib/omnitrace/library/config.hpp, source/lib/omnitrace/library/runtime.cpp, source/lib/omnitrace/library/runtime.hpp, source/lib/omnitrace/library/sampling.cpp
- Prefer using SIGRTMIN + N signals instead of SIGALRM
- OMNITRACE_SAMPLING_KEEP_INTERNAL config option
- OMNITRACE_PROCESS_SAMPLING_FREQ config option
- OMNITRACE_SAMPLING_REALTIME config option
- OMNITRACE_SAMPLING_CPUTIME config option
- OMNITRACE_SAMPLING_REALTIME_OFFSET config option
=> Sampling use SIGRTMIN + N signals

.github/workflows/opensuse.yml, .github/workflows/ubuntu-bionic.yml, .github/workflows/ubuntu-focal.yml, source/lib/omnitrace/library/config.cpp, source/lib/omnitrace/library/debug.hpp, source/lib/omnitrace/library/kokkosp.cpp, tests/CMakeLists.txt
- in certain situations, an exe using kokkos may be instrumented
- this will cause libomnitrace to be dlopened via libomnitrace-dl
- if KOKKOS_PROFILE_LIBRARY is set to libomnitrace and not libomnitrace-dl, you will end up with different instances of libomnitrace trying to collect data
- new OMNITRACE_ABORT macros
- simplifies the definition of test environments
- Adds new tests for KokkosP
=> Fix reliability when KOKKOS_PROFILE_LIBRARY is set in env

source/bin/omnitrace/details.cpp, source/bin/omnitrace/module_function.cpp, source/lib/omnitrace/CMakeLists.txt, source/lib/omnitrace/library.cpp, source/lib/omnitrace/library/components/exit_gotcha.cpp, source/lib/omnitrace/library/components/exit_gotcha.hpp, source/lib/omnitrace/library/components/mpi_gotcha.cpp, source/lib/omnitrace/library/components/pthread_mutex_gotcha.cpp, source/lib/omnitrace/library/components/rocm_smi.cpp, source/lib/omnitrace/library/config.cpp, source/lib/omnitrace/library/runtime.cpp, source/lib/omnitrace/library/runtime.hpp, source/lib/omnitrace/library/state.cpp
- exit gotcha which wraps exit, quick_exit, abort
- this fixes occasional finalization segfault with timemory data when exit is called in code
- minor refactor of mpi gotchas
- removed some redundant code in omnitrace_finalized_hidden
- exclude instrumenting functions starting with dlopen and dlsym
- exclude instrumenting exit, quick_exit, and abort functions
- update timemory submodule with support for new gotcha_invoker with (gotcha_data, <function pointer>, args...)
- improved rocm-smi error handling
=> exit gotcha + remove DelayedInit state + rocm-smi + cleanup

docker/build-docker.sh
- fixes issue where ubuntu cpack workflows for ROCm 5.1 and 5.2 were both building ROCm 5.2
=> ubuntu cpack was building for rocm 5.2 twice

.github/workflows/cpack.yml
- STGZ/DEB/RPM files are in main folder not `build-release/{stgz,deb,rpm}/`
=> Fix uploading release assets

cmake/MacroUtilities.cmake, cmake/Packages.cmake, source/bin/omnitrace-avail/CMakeLists.txt, source/bin/omnitrace-critical-trace/CMakeLists.txt, source/bin/omnitrace/CMakeLists.txt, source/lib/CMakeLists.txt, source/python/CMakeLists.txt
- remove explicit add to CMAKE_INSTALL_RPATH
- remove overriding INSTALL_RPATH_USE_LINK_PATH for exes
- closes #121
=> Fix RPATH handling

.github/workflows/ubuntu-focal.yml, cmake/Modules/Findrocprofiler.cmake, source/bin/CMakeLists.txt, source/bin/omnitrace/CMakeLists.txt, source/lib/CMakeLists.txt
- until v5.2 only librocprofiler64.so was symlinked in /opt/rocm. Thus linker using SOVERSION caused issues finding librocprofiler64.so.1
- closes #121
=> RPATH to rocprofiler_LIBRARY_DIR for ROCm < v5.2

source/lib/omnitrace/library/components/roctracer.cpp, source/lib/omnitrace/library/process_sampler.cpp, source/lib/omnitrace/library/ptl.cpp, source/lib/omnitrace/library/roctracer.cpp
- configure known background threads to start indexing down from TIMEMORY_MAX_THREADS
- invoke `sampling::shutdown()` instead of just blocking signals where possible
=> offset thread ids where possible

CMakeLists.txt, cmake/ConfigInstall.cmake, cmake/Packages.cmake, source/python/CMakeLists.txt, tests/CMakeLists.txt
- When one python version is used, install to proper lib/pythonX.Y/site-packages
- config files, etc. in build tree resemble the install-tree
=> Update python install + build-tree setup

source/lib/omnitrace/library/components/pthread_mutex_gotcha.cpp, source/lib/omnitrace/library/config.cpp, source/lib/omnitrace/library/config.hpp
- `OMNITRACE_TRACE_THREAD_SPIN_LOCKS` configuration setting to wrap `pthread_spin_lock`, `pthread_spin_trylock`, `pthread_spin_unlock`
=> OMNITRACE_TRACE_THREAD_SPIN_LOCKS config

examples/python/CMakeLists.txt, examples/python/noprofile.py, source/python/libpyomnitrace.cpp, source/python/omnitrace/profiler.py, source/python/pyproject.toml, tests/CMakeLists.txt
- `omnitrace.libpyomnitrace.profiler.profiler_pause()`
- `omnitrace.libpyomnitrace.profiler.profiler_resume()`
- Testing for noprofile
In the below, `bar` will show up in the profile but `foo` will not. Using `@noprofile` (or corresponding context-manager) will result in less overhead vs. over excluding functions via command-line regex in `omnitrace-python`
```python
@noprofile
def foo():
pass
@profile
def bar():
foo()
```
=> Python noprofile

source/docs/runtime.md, source/lib/omnitrace/library.cpp, source/lib/omnitrace/library/components/pthread_create_gotcha.cpp, source/lib/omnitrace/library/components/pthread_mutex_gotcha.cpp, source/lib/omnitrace/library/components/pthread_mutex_gotcha.hpp, source/lib/omnitrace/library/config.cpp, source/lib/omnitrace/library/config.hpp, source/lib/omnitrace/library/roctracer.cpp, source/lib/omnitrace/library/runtime.cpp, source/lib/omnitrace/library/runtime.hpp, source/lib/omnitrace/library/sampling.cpp, source/lib/omnitrace/library/thread_info.cpp, source/lib/omnitrace/library/tracing.hpp, tests/CMakeLists.txt
- remove sampling and roctracer flat/timeline options
- unused/unnecessary clutter
- start pthread_gotcha before perfetto
- remove pthread_mutex_gotcha validate
- update timemory submodule with tid fix
=> Support tracing thread locks with perfetto

source/lib/omnitrace/library/components/category_region.hpp, source/lib/omnitrace/library/concepts.hpp, source/lib/omnitrace/library/tracing.hpp
- instead of args="<list-of-string>" in perfetto, each argument is added individually, enabling matching pointer values, etc.
Previously, all function arguments were wrapped into a single string, e.g.:
With the exception of the HIP API (whose args are provided as a single string via `hipApiString`), all functions from MPI, RCCL, pthreads, etc. have individual arguments in perfetto, e.g.:
In the above, previously, this would have been:
|  |  |
| - | - |
| args | `pthread_rwlock_t*=0x1c1cc50` |
The key benefit enabled is the ability to find slices with same arg values:
Previously, the entire "args" field would have had to match, which essentially never happened if the pointer was used in two different functions with different function signatures
=> Individual perfetto debug annotations

source/lib/omnitrace/library/components/numa_gotcha.cpp, source/lib/omnitrace/library/components/numa_gotcha.hpp
- In #152, `numa_alloc_interleaved` and `numa_alloc_local` both were indexed at position 6
=> Fix gotcha indexes for numa_gotcha

cmake/Modules/FindROCmVersion.cmake, cmake/Packages.cmake
=> Fix spack builds when no ROCm .info/version files

examples/transpose/CMakeLists.txt, source/bin/omnitrace/omnitrace.cpp, source/lib/common/setup.hpp, source/lib/omnitrace/library.cpp, source/lib/omnitrace/library/debug.hpp, source/lib/omnitrace/library/roctracer.cpp, source/lib/omnitrace/library/sampling.cpp, tests/CMakeLists.txt
- Raise min instructions default to 1024 instead of 64
- Default value of 64 has demonstrated tendency to slow down real-life applications
- Improved the memory safety during `omnitrace_finalize()`
- new modifications guarantee that when `tim::manager::instance()` on main thread is destroyed, omnitrace will finalize before
- Improved some warning w/ roctracer
- Improved the search for `ROCP_METRICS` and `OMNITRACE_ROCPROFILER_LIBRARY`
- disable printing env by default
- Attempted to improve the sampling shutdown
=> Raise default min number of instructions

source/lib/omnitrace/library/components/category_region.hpp, source/lib/omnitrace/library/tracing.hpp
- The changes in #157 fail to handle situation where multiple arguments have the same type, e.g., `foo(int a, int b)` where `a=1` and `b=2` would result in one debug annotation `int: 1`
- Now include the position number of the argument, e.g. `arg1-int` and `arg2-int`.
- Closes #180
=> Fix perfetto debug annotations of function parameters

source/lib/omnitrace/library/config.cpp
- OMNITRACE_ROCTRACER_HSA_ACTIVITY is OFF by default
- OMNITRACE_ROCTRACER_HSA_API is OFF by default
- in real applications, this adds way too much tracing data to perfetto
=> Disable HSA API and activity by default

cmake/MacroUtilities.cmake, source/bin/omnitrace-avail/CMakeLists.txt, source/bin/omnitrace-sample/CMakeLists.txt, source/lib/omnitrace-dl/dl.cpp, source/lib/omnitrace-dl/main.c, source/lib/omnitrace/api.cpp, source/lib/omnitrace/api.hpp, source/lib/omnitrace/library.cpp
- __libc_start_main in libomnitrace-dl wasn't wrapping bc of -fvisibility=hidden
- fix OMNITRACE_STRIP_TARGET
- omnitrace_reset_preload function in main library
- defer removing libomnitrace from LD_PRELOAD
=> Fix LD_PRELOAD

source/bin/omnitrace-avail/avail.cpp, source/docs/output.md, source/lib/omnitrace/library.cpp, source/lib/omnitrace/library/config.cpp, source/lib/omnitrace/library/config.hpp, source/lib/omnitrace/library/perfetto.hpp, source/lib/omnitrace/library/sampling.cpp, tests/CMakeLists.txt
- update timemory submodule
- support for load/save of ring_buffers
- new output keys, e.g. `%nid%`
- sampling allocator offloading data
- writing sampling data to temporary file
- new advanced config option `OMNITRACE_USE_TEMPORARY_FILES`
- new advanced config option `OMNITRACE_TMPDIR`
- SIGINT signal (i.e. `Ctrl+C`) triggers backtrace + finalization
- this behavior is common to other profilers
=> Offload sampling data

.github/workflows/ubuntu-focal.yml
`/sbin/ldconfig -p` in Ubuntu 22.04 has line at the end similar to following:
```console
... etc. ...
ld-linux-x86-64.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
... etc. ...
Cache generated by: ldconfig (Ubuntu GLIBC 2.35-0ubuntu3.1) stable release version 2.35
```
The previous implementation for reading the ld cache would overflow the stack when it tried to parse this line.
Note: the testing largely relies on pre-built Dyninst instances which are rebuilt nightly so this fix will not have an immediate effect.
=> Dyninst fix for BinaryEdit::getResolvedLibraryPath

source/bin/omnitrace/omnitrace.cpp, source/lib/omnitrace/library/config.cpp, source/lib/omnitrace/library/config.hpp, source/lib/omnitrace/library/sampling.cpp
- dynamic sampler is constructed with a shared pointer to an allocator instance
- allocator handles multiple samplers
- eliminates need for every per-thread dynamic sampler to start background allocator thread
- reduces number of background threads
- supports starting all background allocator threads during initialization
- new advanced configuration variable `OMNITRACE_SAMPLING_ALLOCATOR_SIZE`
- number of sampler instances handled by allocator
- new advanced configuration variable `OMNITRACE_NUM_THREADS_HINT`
- hint for number of threads created by app, when set appropriately, sampling will start all required allocator threads during initialization
- timemory submodule was updated with various fixes for its own tests
=> Improve sampling allocator

.github/workflows/cpack.yml, .github/workflows/opensuse.yml, .github/workflows/ubuntu-bionic.yml, .github/workflows/ubuntu-focal.yml, .github/workflows/ubuntu-jammy.yml, docker/build-docker.sh, scripts/run-ci.py, source/lib/omnitrace/library/config.cpp, source/lib/omnitrace/library/config.hpp, source/lib/omnitrace/library/roctracer.cpp, source/lib/omnitrace/library/roctracer.hpp, source/lib/omnitrace/library/tracing.cpp, source/lib/omnitrace/library/tracing.hpp
- Includes general idea behind #201
- Closes #208 
- New configuration variable `OMNITRACE_PERFETTO_ROCTRACER_PER_STREAM`
- Default value is `ON`
- Disabling this option will group all GPU activity per-device
- There is not config option for disabling per-device GPU activity
- Handle HSA OPS in ROCm 5.3
- The changes in ROCm 5.3 were causing HSA ops to get discarded
- Default for `OMNITRACE_ROCTRACER_DISCARD_INVALID` environment variable is now zero
- i.e. default behavior is to flip begin and end timestamps when begin > end
=> roctracer: device and stream tracks

docker/build-docker-release.sh, docker/build-docker.sh, source/bin/omnitrace-critical-trace/critical-trace.cpp, source/lib/omnitrace/library/components/backtrace_metrics.cpp, source/lib/omnitrace/library/components/backtrace_metrics.hpp, source/lib/omnitrace/library/components/exit_gotcha.cpp, source/lib/omnitrace/library/components/exit_gotcha.hpp, source/lib/omnitrace/library/critical_trace.cpp, source/lib/omnitrace/library/critical_trace.hpp, source/lib/omnitrace/library/ompt.cpp, source/lib/omnitrace/library/sampling.cpp
- critical trace update
- use ::perfetto::Track instead of threads to create rows
- refactor call_chain::generate_perfetto
- fix backtrace_metrics for perfetto
- get_papi_labels is now properly populated
- closes #210 
- refactor sampling::post_process_perfetto
- include HW counter delta in sample debug annotations
- reduce the amount debug annotation data stored in the call-stack
- if the data is common to the entire stack, it is only annotated in the first and the last call-stack entry
=> Perfetto updates

source/lib/omnitrace/library/rocm.cpp
Add another version checked initialiation, because: [roctracer has changed `hsa_ops_properties_t` again in 5.3.1][hsa_ops_properties_t]
[hsa_ops_properties_t]: https://github.com/ROCm-Developer-Tools/roctracer/compare/rocm-5.3.0...rocm-5.3.1#diff-42ffacd4e7f57213868dcd96aeb5c0d47d91d2a1121ba8d67f46caa267c1818cL41
Fixes: #213
=> rocm: Fix compilation with rocm >= 5.3.1

.github/workflows/cpack.yml, .gitignore, cmake/Templates/omnitrace-install.py.in, scripts/write-omnitrace-install.cmake
- omnitrace-install.py will be uploaded as a release asset
- script simplifies selecting the correct installer script
```console
ARG OMNITRACE_VERSION=latest
ARG ROCM_VERSION=5.3
RUN wget https://github.com/AMDResearch/omnitrace/releases/download/${OMNITRACE_VERSION}/omnitrace-install.py && \
python3 omnitrace-install.py --rocm ${ROCM_VERSION} && \
rm omnitrace-install.py
```
```console
$ python3 omnitrace-install.py --help
usage: omnitrace-install.py [-h] [--version] [-p PREFIX] [-i]
[-D DOWNLOAD_PATH] [-d {auto,ubuntu,opensuse}]
[-v OS_VERSION] [-k]
[--rocm [VERSION or ROCM_PATH with .info/version files]]
[-e [{papi,ompt,python3} [{papi,ompt,python3} ...]]]
optional arguments:
-h, --help            show this help message and exit
--version             Print omnitrace version which will …
```
=> omnitrace-install.py

docker/Dockerfile.opensuse, source/lib/omnitrace/library.cpp, source/lib/omnitrace/library/components/roctracer.cpp, source/lib/omnitrace/library/config.cpp, source/lib/omnitrace/library/config.hpp
- new configuration options: `OMNITRACE_ROCTRACER_HIP_API` and `OMNITRACE_ROCTRACER_HIP_ACTIVITY`
- formerly whenever `OMNITRACE_USE_ROCTRACER` was `ON`, there was no option to turn off tracing the HIP API will still tracing kernels (activity) or vice versa
- `OMNITRACE_ROCTRACER_HIP_API`: enable/disable tracing HIP API function calls
- `OMNITRACE_ROCTRACER_HIP_ACTIVITY`: enable/disable tracing HIP kernels
- Named similarly to `OMNITRACE_ROCTRACER_HSA_API` and `OMNITRACE_ROCTRACER_HSA_ACTIVITY`
- Similar to HSA options, the values of these settings are meaningless if `OMNITRACE_USE_ROCTRACER` is `OFF`
- In previous PR (~#190), omnitrace started always generating a `metadata.json` and `functions.json` as `metadata-<PID>.json` and `functions-<PID>.json` regardless of the setting of …
=> HIP API and Activity Config Options + metadata JSON PID tagging

CMakeLists.txt, cmake/MacroUtilities.cmake, source/bin/omnitrace-causal/impl.cpp, source/lib/omnitrace/library/causal/components/backtrace.cpp, source/lib/omnitrace/library/causal/components/backtrace.hpp, source/lib/omnitrace/library/causal/components/blocking_gotcha.cpp, source/lib/omnitrace/library/causal/components/blocking_gotcha.hpp, source/lib/omnitrace/library/causal/components/unblocking_gotcha.cpp, source/lib/omnitrace/library/causal/components/unblocking_gotcha.hpp, source/lib/omnitrace/library/causal/data.cpp, source/lib/omnitrace/library/causal/delay.cpp, source/lib/omnitrace/library/causal/sampling.cpp, source/lib/omnitrace/library/causal/sampling.hpp, tests/validate-causal-json.py
- corrections in the calculations for latency and throughput points in `validate-causal-json.py`
- `omnitrace-causal` LD_PRELOAD libpthread
- ensures omnitrace is always wrapping libpthread.so pthread symbols
- minimal experiment delay
- always sleep 10 milliseconds before starting experiments
- ensures ~10 samples are taken to determine the sampling rate
- fixes issue with deadlocks on condition variables
- overhaul of `causal::component::blocking_gotcha` and `causal::component::unblocking_gotcha` components
- these components enforce the processing/crediting of delays before/after a thread is suspended
- these components wrap functions `pthread_cond_wait`, `pthread_cond_signal`, `pthread_mutex_lock`, etc.
- Fully implemented correct handling of processing/crediting delays based on …
=> Causal profiling fixes

source/lib/omnitrace/library/kokkosp.cpp
- Error: `internal compiler error: output_operand: '%&' used without any local dynamic TLS references`
- location: kokkosp.cpp
- causing cpack packaging to fail
=> Fix internal gcc compiler error for GCC 7

source/python/gui/source/gui.py, source/python/gui/source/parser.py
I am going to merge this but it is using the wrong standard deviation data. The error bars should reflect the experiment progress point standard deviation at a specific virtual speedup, not the impact standard deviation. In other words, the error bar should show how much variance is in the virtual speedup prediction.
=> Causal profiling GUI: error bars

source/python/gui/source/__main__.py, source/python/gui/source/gui.py, source/python/gui/source/header.py, source/python/gui/source/parser.py
-Now accepts multiple jsons in directory
-samples error fix
-light mode now an option
-select which file to present data from dropdown
(Does not work with histogram yet)
-workload added to dataframe
-More color options
=> Multiple files now read from directory

cmake/Templates/omnitrace-install.py.in
- handle blank lines in /etc/os-release
=> fix omnitrace-install.py script

source/lib/common/environment.hpp, source/lib/common/path.hpp, source/lib/common/setup.hpp, source/lib/omnitrace/library/roctracer.cpp
- Improve locating `ROCP_METRICS` file
- check for `metrics.xml` and `gfx_metrics.xml` before setting ROCP_METRICS
- throw error if path for ROCP_METRICS is cannot be explicitly determined
- moved `common::path::*` to `common/path.hpp`
- added more functionality to `common::path`
- `common::path::exists(...)` now returns true for directories
- Fix `roctxRangePop` handling
- requires `roctxRangePush` and `roctxRangePop` to be on same thread
- closes #259
=> rocprofiler and roctx updates

source/lib/omnitrace/library/rocm/hsa_rsrc_factory.cpp
- Revert `agent_info->dev_index` to use old method in `hsa_rsrc_factory.cpp`
- disable using the driver_node_id and, instead, start at zero because it breaks the lookup for `rocprofiler_pool_fetch` lookup in `rocprofiler.cpp`. On my system (one AMD GPU and one NVIDIA GPU), it has a value of 1, not 0 and the pool size is 1 leading to a segfault
- Fixes #268
=> rocprofler_iterate_info workaround v2

.github/workflows/python.yml, source/python/gui/setup.cfg, source/python/gui/setup.py, source/python/gui/source/__main__.py, source/python/gui/source/gui.py, source/python/gui/source/header.py, source/python/gui/source/parser.py
- Error bars for causal data
- the +/- values were treated as percents of original value when in reality they were values
- Mislabeled `function_regex` and `exp_regex`
- in the code, progress points were misinterpreted as "experiments" when, in fact, the function/line stuff was the experiments
- Unused dataframe creation in `add_latency`
- Latency points not showing up in plots from JSON data
- looking for "arrivals" key instead of "arrival"
- `latency_point` class had duplicate `__init__` functions
- `--stddev` argument unused
- not effectively assigned to `num_stddev` in `parser.py`
- Workflow which runs flake8 on `source/python/gui` files
- Removed numerous unused by assigned variables (flake8 linting error)
- Removed numerous unused imports (flake8 linting error)
- Replaced `if X == …
=> Causal GUI: Linting, synced y-range, remove unused imports/variables, and bug fixes

.github/workflows/redhat.yml, .github/workflows/ubuntu-jammy.yml, docker/Dockerfile.opensuse, docker/Dockerfile.rhel, docker/build-docker.sh
- amdgpu-install use case hiplibsdk is not necessary and bloats the install
- same as above for package rocm-hip-sdk
=> Remove docker hiplibsdk from amdgpu-install

source/lib/core/config.cpp, source/lib/omnitrace/library/kokkosp.cpp
- disable tracing deep copies by default because inconsistent begin/end corrupts call-stack hierarchy
- tracing deep copy operations can be enabled via `OMNITRACE_KOKKOSP_DEEP_COPY`
=> kokkosp update: disable deep copy tracing by default

.github/workflows/containers.yml, .github/workflows/cpack.yml, .github/workflows/opensuse.yml, .github/workflows/redhat.yml, .github/workflows/ubuntu-bionic.yml, .github/workflows/ubuntu-focal.yml, .github/workflows/ubuntu-jammy.yml, docker/Dockerfile.opensuse, docker/Dockerfile.rhel, docker/build-docker.sh
- Support ROCm 5.5 in docker builds
- Update containers workflow
- add Ubuntu and OpenSUSE container builds for ROCm 5.4 and 5.5
- add RHEL builds
- Update CPack workflow
- build on PR against main when cpack.yml or docker files updated
- removed packaging for ROCm < 5.2 for many OSes
- added packaging for ROCm 5.5
- Update OpenSUSE workflow
- add python 3.11 to `OMNITRACE_PYTHON_ENVS` (creates additional tests)
- upload-artifacts name includes strategy.job-index (prevent overwrite)
- only upload artifacts on failure
- continue on error if upload artifacts fails
- Update RedHat workflow
- provide run-name
- add python 3.11 to `OMNITRACE_PYTHON_ENVS` (creates additional tests)
- upload-artifacts name includes strategy.job-index (prevent overwrite)
- only upload artifacts on failure
- …
=> GitHub Actions workflow and docker updates

source/python/omnitrace/__main__.py
- fixes issue where forking process in PyTorch causes `omnitrace/__main__.py` to fail due to missing script argument
- closes #284
Follow basic setup steps in #284. 
> Note: on system used for testing (Lockhart) `LD_PRELOAD=/usr/lib64/libstdc++.so.6` was required due to `libstdc++.so.6` from conda env being too old for the ROCm libraries linked by omnitrace (omnitrace was built with `-static-libstdcxx`)
1. Configure stemdlConfig.yaml with 2 GPUs and execute `srun -G 2 python -m omnitrace -- ./stemdl_classification.py --config ./stemdlConfig.yaml`
2. Configure stemdlConfig.yaml with 4 GPUs and execute `srun -G 4 python -m omnitrace -- ./stemdl_classification.py --config ./stemdlConfig.yaml`
3. Wrote `run.sh` and execute `srun -G 2 ./run.sh`
```shell
#!/bin/bash
set +e
pkill traced
pkill …
```
=> PyTorch Python fork fix

source/python/omnitrace/__main__.py
- store script file in environment for robustness against restart after fork
- closes #284
=> PyTorch Python fork fix part 2

source/docs/causal_profiling.md, source/docs/critical_trace.md, source/docs/output.md
1. To build the example code in causal_profiling.md with g++ seems need a bit changes(Maybe we don't want to tie it up to specific compiler, but it is good to post code user can try it right away)
2. Other modifications just typo.
=> A few fixes for the document

source/lib/omnitrace/library/roctracer.cpp
- roctracer_type_mutex was per-thread, causing lack of sync b/t callback and activity
- closes #304
=> Fix roctracer data race

tests/omnitrace-mpi-tests.cmake
The CI test machines only have 2 MPI slots. MPI tests were failing when requesting 4 slots. Update these tests to request 2 slots.
Tested on CI docker image with MPI configured to have 2 slots.
=> Fix MPI test failures

cmake/Templates/setup-env.sh.in
This PR enables calling `source setup-env.sh` from non-bash shells (tested on zsh) by falling back to `$0` for detecting the script's path.
=> Enable running setup-env from non-bash shells

source/lib/core/config.cpp, source/lib/omnitrace/library/roctracer.cpp
When inspecting traces with multiple queues, barrier events can be overwhelming on the profile. This PR creates a config entry to not include those in the output file. The configuration is disabled by default, so it should not affect the existing behavior.
=> Add option to skip barrier marker events in traces

source/lib/core/gpu.cpp
- Update lib/core/gpu.cpp
- use `const std::array` instead of `constexpr std::array` due to internal compiler errors on systems with older GCC compilers
=> Fix cpack on SLES

source/lib/omnitrace/library/components/roctracer.cpp, source/lib/omnitrace/library/roctracer.cpp
- fix call to `hip_exec_activity_callbacks` when more runtime threads than compile time max threads
=> Fix thread-limit bug in roctracer

source/docs/installation.md
Now pointing to https://rocm.docs.amd.com/projects/install-on-linux/en/latest/.
=> Fix link to ROCm install instructions

source/bin/omnitrace-avail/avail.cpp, source/bin/omnitrace-avail/common.hpp
- flush stdout when listing keys to prevent overlap with stderr logging
- Report GPU device count at verbose level 1 instead of 0
=> Flush stdout when listing keys + bump verbose level for GPU count

source/lib/core/gpu.cpp
It is causing failures on our internal builds
=> Removing static version asserts.

.github/workflows/docs.yml, .github/workflows/opensuse.yml, .github/workflows/ubuntu-bionic.yml, source/bin/omnitrace-sample/impl.cpp, source/lib/core/argparse.cpp, source/lib/omnitrace/library/thread_info.cpp, tests/source/CMakeLists.txt
- Use OMNITRACE_TRACE and OMNTRACE_PROFILE instead of perfetto/timemory
- Update timemory submodule
- argparse: requires -> required (requires is reserved keyword in C++20)
- parse callbacks for settings
- Update thread_info.cpp
- fix `causal::delay::get_local()` usage which is causing error on some systems
=> Workflow, submodules, and thread info Updates

source/bin/omnitrace-run/impl.cpp, source/bin/omnitrace-sample/impl.cpp, source/bin/omnitrace-sample/omnitrace-sample.hpp, source/lib/core/argparse.cpp, source/lib/core/argparse.hpp
- `omnitrace-run`, `omnitrace-sample`, and `omnitrace-causal` now automatically append the `LD_LIBRARY_PATH` with the directory containing the omnitrace libraries
- this helps ensure that binary rewritten exes can resolve omnitrace-rt library location
Algorithm is essentially as follows:
```console
OMNITRACE_BIN_DIR=$(dirname $(which omnitrace-run))
OMNITRACE_LIB_DIR=$(realpath ${OMNITRACE_BIN_DIR}/../lib)
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${OMNITRACE_LIB_DIR}
```
=> Executables append omnitrace library directory to LD_LIBRARY_PATH

cmake/ElfUtils.cmake
Override the default URL used to download ElfUtils and BinUtils. Useful for internal builds
Also, include a mirror to fallback to if the override URL fails.
Updates Timemory submodule.
=> Add ElfUtils and BinUtils Download URL Overrides

docker/Dockerfile.rhel, docker/Dockerfile.rhel.ci, docker/Dockerfile.ubuntu, docker/Dockerfile.ubuntu.ci
`makeinfo` was not found, so I updated the docker files to include `texinfo`.
For Ubuntu, I also had to add `bison`.
=> This fixes the CPACK workflow failures for Ubuntu and RHEL

source/lib/omnitrace/library/components/roctracer.cpp
- Revert part of [blamed commit](https://github.com/ROCm/omnitrace/pull/78/commits/b134a68110b2c96ce11293d93ad56f38e211fd06) modifying source/lib/omnitrace/library/components/roctracer.cpp with goal of  "clear roctracer_data storage if roctracer not initialized"
- Particularly, I don't think ```tim::storage<comp::roctracer_data>::instance()``` returns the instance of the storage singleton if it exists, but rather creates an empty unique_ptr to the storage type
=> Fix SWDEV-473314 by avoiding empty unique_ptr dereference

.github/workflows/containers.yml, .github/workflows/cpack.yml, .github/workflows/docs.yml, .github/workflows/formatting.yml, .github/workflows/opensuse.yml, .github/workflows/python.yml, .github/workflows/redhat.yml, .github/workflows/ubuntu-focal.yml, .github/workflows/ubuntu-jammy.yml, docs/index.rst, docs/reference/development-guide.rst, docs/sphinx/_toc.yml.in, source/docs/development.md
There is a Dev-Ops request to use standard branch names for our staging and main branches. This change is prep work for that.
main --> amd-mainline
Will create amd-staging.
New branch names have been added to workflows. However, old branch names will not be removed until renaming is complete.
=> Prepare for branch renaming. 
