ROCm/omnitrace

- source/docs/output.md
- "CPU_FEATURES" entry is not a JSON array, not a string
- Adds examples of "memory_maps" and "memory_map_files"
- Provides a list overview of the contents
> Documentation on metadata JSON file [skip ci]

- examples/CMakeLists.txt
- scripts/omnitrace_launch_compiler
- source/lib/omnitrace/library.cpp
- source/lib/omnitrace/library/components/fwd.hpp
- source/lib/omnitrace/library/thread_sampler.cpp
- Fixed some clang-tidy warnings
- Fixed issue with omnitrace_launch_compiler + clang-tidy
> clang-tidy

- .github/workflows/cpack-opensuse.yml
- .github/workflows/cpack-ubuntu.yml
> Update cpack workflows

- examples/.gitignore
- examples/CMakeLists.txt
- examples/code-coverage/CMakeLists.txt
- examples/lulesh/CMakeLists.txt
- examples/lulesh/external/CMakeLists.txt
- examples/mpi/CMakeLists.txt
- examples/openmp/CMakeLists.txt
- examples/parallel-overhead/CMakeLists.txt
- examples/parallel-overhead/parallel-overhead.cpp
- examples/python/CMakeLists.txt
- examples/transpose/CMakeLists.txt
- examples/user-api/CMakeLists.txt
- OMNITRACE_INSTALL_EXAMPLES option
- Fix lulesh standalone HIP compilation
- Fix transpose standalone HIP compilation
- Tweaks to parallel-overhead
> CMake updates/fixes + parallel-overhead updates

- source/docs/youtube.md
- replaced videos with poor audio with videos which are better
> Update youtube links

- source/docs/runtime.md
- example config file will fail due to #31 
- Closes #40
> Fixes the configuration file example

- source/lib/common/invoke.hpp
- source/lib/common/join.hpp
- source/lib/omnitrace-dl/dl.cpp
> Fix find_path in omnitrace-dl

- source/bin/omnitrace-avail/generate_config.cpp
- source/lib/omnitrace/library/config.cpp
- tests/CMakeLists.txt
> Fix empty OMNITRACE_CONFIG_FILE and suppressing config and parsing

- source/bin/omnitrace-critical-trace/critical-trace.cpp
- source/lib/omnitrace/library.cpp
- source/lib/omnitrace/library/components/backtrace.cpp
- source/lib/omnitrace/library/components/fork_gotcha.cpp
- source/lib/omnitrace/library/components/pthread_create_gotcha.cpp
- source/lib/omnitrace/library/components/rocm_smi.cpp
- source/lib/omnitrace/library/config.cpp
- source/lib/omnitrace/library/critical_trace.cpp
- source/lib/omnitrace/library/process_sampler.cpp
- source/lib/omnitrace/library/roctracer.cpp
- source/lib/omnitrace/library/runtime.cpp
> Replaces OMNITRACE_CONDITIONAL_BASIC_PRINT with OMNITRACE_VERBOSE

- cmake/BuildSettings.cmake
- source/lib/omnitrace/library/debug.hpp
- Fix warnings via OMNITRACE_BASIC_VERBOSE and OMNITRACE_BASIC_VERBOSE_F
- CMake option OMNITRACE_BUILD_DEVELOPER adds -Werror when ON
> Fix warnings + Werror

- cmake/PAPI.cmake
- docker/Dockerfile.centos
- docker/Dockerfile.opensuse
- docker/Dockerfile.ubuntu
- scripts/build-release.sh
- Release Docker uses CMake 3.21.4
- Configurable PAPI_C_COMPILER
- build-release.sh builds install
> Docker + build-release.sh + PAPI.cmake

- source/lib/common/environment.hpp
- source/lib/omnitrace/library.cpp
- source/lib/omnitrace/library/cpu_freq.cpp
- source/lib/omnitrace/library/timemory.hpp
- Improved error handling in getenv
- write_perfetto_counter_track
> Minor fixes

- examples/python/source.py
- source/python/CMakeLists.txt
- source/python/libpyomnitrace.cpp
- source/python/omnitrace/__init__.py
- source/python/omnitrace/common.py
- source/python/omnitrace/profiler.py
- source/python/omnitrace/user.py
- tests/CMakeLists.txt
- tests/validate-timemory-json.py
- e.g. `omnitrace.user.push_region("foo")` and `omnitrace.user.pop_region("foo")`
> User regions in Python

- source/bin/omnitrace-avail/generate_config.cpp
- also smart deduction of output format
> Handle --advanced printing for config generation

- CMakeLists.txt
- cmake/Packages.cmake
- source/lib/omnitrace/CMakeLists.txt
- source/lib/omnitrace/library/components/backtrace.cpp
- source/lib/omnitrace/library/components/backtrace.hpp
- source/lib/omnitrace/library/sampling.cpp
- provides addr2line information for sampling
> Support for libbfd (binary file descriptor)

- source/bin/omnitrace/omnitrace.cpp
- source/lib/omnitrace/library.cpp
- source/lib/omnitrace/library/components/mpi_gotcha.cpp
- source/lib/omnitrace/library/components/pthread_create_gotcha.cpp
- source/lib/omnitrace/library/components/pthread_mutex_gotcha.cpp
- source/lib/omnitrace/library/components/roctracer.cpp
- source/lib/omnitrace/library/config.cpp
- source/lib/omnitrace/library/debug.hpp
- source/lib/omnitrace/library/ompt.cpp
- source/lib/omnitrace/library/rocm.cpp
- source/lib/omnitrace/library/roctracer.cpp
- source/lib/omnitrace/library/roctracer.hpp
- source/lib/omnitrace/library/sampling.cpp
- update timemory submodule with fixes to papi components and signals update
> Fix finalization segfaults

- .github/workflows/containers.yml
- .github/workflows/cpack.yml
- .github/workflows/formatting.yml
- .github/workflows/opensuse.yml
- .github/workflows/ubuntu-bionic.yml
- .github/workflows/ubuntu-focal.yml
- .github/workflows/ubuntu-jammy.yml
- README.md
- cmake/BuildSettings.cmake
- cmake/MacroUtilities.cmake
- source/bin/omnitrace/CMakeLists.txt
- source/bin/omnitrace/details.cpp
- source/bin/omnitrace/log.cpp
- source/bin/omnitrace/log.hpp
- source/bin/omnitrace/omnitrace.cpp
- source/lib/omnitrace/library.cpp
- source/lib/omnitrace/library/config.cpp
- source/lib/omnitrace/library/config.hpp
- source/lib/omnitrace/library/debug.hpp
- print line info when termination signal handler is invoked (e.g. after segfault, etc.) 
- print backtrace after SIGINT during finalization
> Signal handler backtraces provide line info

- source/lib/omnitrace/library/critical_trace.cpp
- source/lib/omnitrace/library/critical_trace.hpp
- source/lib/omnitrace/library/rocm_smi.cpp
- several orders of magnitude faster
- closes #172
> Dramatic improvement of post-processing critical trace data

- source/lib/omnitrace/library/roctracer.cpp
- only print N warnings that end < begin
- if N is zero, swap(begin, end) and include data
> OMNITRACE_ROCTRACER_DISCARD_INVALID=N

- .github/workflows/opensuse.yml
- .github/workflows/ubuntu-bionic.yml
- .github/workflows/ubuntu-focal.yml
- .github/workflows/ubuntu-jammy.yml
- CMakeLists.txt
- cmake/BuildSettings.cmake
- cmake/MacroUtilities.cmake
- cmake/Modules/FindMPI-Headers.cmake
- cmake/Packages.cmake
- examples/code-coverage/CMakeLists.txt
- examples/lulesh/CMakeLists.txt
- examples/mpi/CMakeLists.txt
- examples/parallel-overhead/CMakeLists.txt
- examples/python/CMakeLists.txt
- examples/rccl/CMakeLists.txt
- examples/transpose/CMakeLists.txt
- examples/user-api/CMakeLists.txt
- scripts/run-ci.sh
- source/bin/omnitrace/omnitrace.cpp
- source/bin/omnitrace/omnitrace.hpp
- source/lib/omnitrace/library/components/backtrace.cpp
- source/lib/omnitrace/library/kokkosp.cpp
- source/lib/omnitrace/library/rocprofiler.cpp
- tests/CMakeLists.txt
- improve finalization time of rocprofiler
- decrease the build time of timemory
- remove kokkosp perfetto restrictions
- reduce memory by disabling BFD parsing when `OMNITRACE_SAMPLING_INCLUDE_INLINES` is OFF
> Various optimizations

- .github/workflows/cpack.yml
- Fixes error in CPack workflow from PR #203
> CI CPack fix

- docker/Dockerfile.opensuse
- docker/build-docker.sh
> Fix OpenSUSE ROCm install for CPack workflow

- .github/workflows/cpack.yml
- docker/build-docker.sh
- add ROCm 5.4 to CPack variants
> CPack support for ROCm 5.4

- CMakeLists.txt
- cmake/PAPI.cmake
- cmake/Packages.cmake
- examples/causal/impl.cpp
- source/bin/omnitrace/details.cpp
- source/bin/omnitrace/internal_libs.cpp
- source/bin/omnitrace/omnitrace.cpp
- source/docs/installation.md
- source/lib/CMakeLists.txt
- source/lib/binary/address_multirange.cpp
- source/lib/binary/link_map.cpp
- source/lib/core/CMakeLists.txt
- source/lib/omnitrace/CMakeLists.txt
- source/lib/omnitrace/library/causal/components/backtrace.cpp
- source/lib/omnitrace/library/causal/components/causal_gotcha.cpp
- source/lib/omnitrace/library/causal/components/causal_gotcha.hpp
- source/lib/omnitrace/library/causal/data.cpp
- source/lib/omnitrace/library/causal/delay.cpp
- source/lib/omnitrace/library/causal/sampling.cpp
- tests/validate-causal-json.py
- closes #236 
- closes #232 
- closes #194 
- closes https://github.com/NERSC/timemory/issues/253
> Misc fixes before v1.8.0 release

- .github/workflows/formatting.yml
- .github/workflows/opensuse.yml
- .github/workflows/ubuntu-bionic.yml
- .github/workflows/ubuntu-focal.yml
- .github/workflows/ubuntu-jammy.yml
- source/python/gui/source/__main__.py
- source/python/gui/source/gui.py
- source/python/gui/source/parser.py
- tests/validate-causal-json.py
- read in call-stack samples and generate bar graph
- reorder display so that call-stack histogram is at bottom
> Call stack sample histogram

- .github/workflows/redhat.yml
- source/python/gui/source/__main__.py
- source/python/gui/source/assets/layout.css
- Remove duplicate -l / --light argument
- Add missing "multi" dict entries for input filters
- Updated redhat.yml workflow to ignore changes to `source/python/gui/**`
> Fix Causal GUI PR #260

- source/python/gui/source/__main__.py
- source/python/gui/source/gui.py
- source/python/gui/source/parser.py
- gui fixes removing verbosity
- parser.parse_files returns filenames
- parser.parse_files handles verbosity
- parser.parse_files handles settings
- improved main
- call parse_files
- support recursive glob
- improved settings support
- support ~/.omnitrace-causal-plot.json
> Miscellaneous Causal GUI Fixes

- .github/workflows/containers.yml
- docker/Dockerfile.rhel
- docker/Dockerfile.rhel.ci
- docker/build-docker-ci.sh
- avoid `yum update` since that can update the distro minor version
> Fix RHEL docker containers

- source/lib/omnitrace/library/rocm.cpp
- starting with ROCm 5.5.0, rocprofiler throws exception if OnLoad + dlopen librocprofiler
- CI skipped for this PR since CI does not support GPU usage (tested locally)
> Fix rocprofiler usage in ROCm >= 5.5.x

- source/lib/omnitrace/library/sampling.cpp
- avoid creating overflow sampling tracks in Perfetto when there is no data
- fix the parent region begin/end timestamps for the sampling tracks
> Sampling post-processing Perfetto fix

- .github/workflows/cpack.yml
- .github/workflows/opensuse.yml
- .github/workflows/redhat.yml
- .github/workflows/ubuntu-bionic.yml
- .github/workflows/ubuntu-focal.yml
- .github/workflows/ubuntu-jammy.yml
- docker/Dockerfile.opensuse
- docker/Dockerfile.opensuse.ci
- docker/build-docker.sh
> ROCm 6.0 packaging

- source/python/libpyomnitrace.cpp
Protect from possible seg. fault
> Check for an empty vector before popping

- .github/workflows/cpack.yml
* Add rocm tag to cpack.yml
* Update softprops/action-gh-release to v2
> Add rocm tag to cpack.yml
